---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hajimari
  namespace: services
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  values:
    controller:
      replicas: 3
      strategy: RollingUpdate
    hajimari:
      title: NatFlix
      lightTheme: tron
      darkTheme: tron
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: false
      showAppStatus: true
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      showAppInfo: true
      defaultEnable: true
      defaultAppIcon: mdi:application
      defaultSearchProvider: Whoogle
      namespaceSelector:
        matchNames:
          - media
          - network
          - services
      customApps:
      globalBookmarks:
        - group: Dev
          bookmarks:
            - name: GitHub
              url: "https://github.com"

        - group: Games
          bookmarks:
            - name: Lichess
              url: "https://lichess.org"


      searchProviders:
        - name: Google
          token: g
          icon: simple-icons:google
          searchUrl: https://www.google.com/search?q={query}
          url: https://www.google.com
        - name: IMDB
          token: i
          icon: simple-icons:imdb
          searchUrl: https://www.imdb.com/find?q={query}
          url: https://www.imdb.com
        - name: YouTube
          token: "y"
          icon: simple-icons:youtube
          searchUrl: https://www.youtube.com/results?search_query={query}
          url: https://www.youtube.com
        - name: Spotify
          token: s
          icon: simple-icons:spotify
          searchUrl: hhttps://open.spotify.com/search/{query}
          url: https://open.spotify.com
        - name: WolframAlpha
          token: w
          icon: simple-icons:wolfram
          searchUrl: https://www.wolframalpha.com/input?i={query}
          url: https://www.wolframalpha.com
    ingress:
      main:
        enabled: true
        ingressClassName: "internal-nginx"
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: "hajimari.${EXTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hajimari.${EXTERNAL_DOMAIN}"
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 64M