apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr
  namespace: default
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NFS_IP}
    path: "/config/prowlarr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr
  namespace: default
spec:
  storageClassName: manual
  volumeName: prowlarr-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M