apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reverse-proxy
spec:
  interval: 5m
  chart:
    spec:
      chart: reverse-proxy
      version: 3.0.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu-helm-charts
        namespace: flux-system

  values:
    instances:
    - name: home-assistant
      ip: 192.168.0.2
      port: 443
      ingress:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: Router
          hajimari.io/icon: router
          hajimari.io/info: Router
          hajimari.io/group: network
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
        - host: ha.rphilipsen.nl
