apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:iKTE72S9M8GQDadUVb4W//sSCTY7szrFiDqJTXt+uV3u33wi,iv:uslacNQZsWEj8Y5SXCGA8HSPFe1thVsL34ZExg875vM=,tag:OCcKrRGLZnWNipr7TN68dw==,type:str]
    credentials.json: ENC[AES256_GCM,data:ksRYsGMOulUR7QEOh/jM3pXYbOkjNaZTP0DjYkBGgUZhilAqY/bzpjc+K9NyRR0qdD02XKFxJhabebDqKODvB4ql8pmpKvEtgUTSiG6BtoPdLfopFc+SxZLtR6Py2OrnPa9c2R1yDrXbtLcGbGtj9Xw2B4whB30/w0jvhIHubWkF73RzrUzeZ8sv/zsYTcneb8wf3ZUUw1CFA/YSOHZoho23mh+4RcWUod8g/Kh1TA==,iv:S+88kCQ9boa5PZ/6v1hT5q8k/QMTmE1UErl4VQFqpvw=,tag:JkOXL+GFWxTD3KxX/qx0Cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdqved3s25mcpgt3r3wgckez60u8jr5aj8espeda88uyh9h3wqpqzj49yr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqa1BERUpVVWN5RVo1TWwx
            UEdKdDRxTFYwNmNQZmhSRVFHUFZuMkttNm5FCjB5UDBnZmR6dWErbi9tY2phcTB4
            U1JNblhKN1ZnYlBUTlVsYmVGelJtem8KLS0tIC9tMzlLREJ5bU15YmMvSlBDakpB
            Z1dQaFVNSEpDZ0JVMERkQ2poaDdKbFUK4addPdLokDib+mz1kimFQNRDgw46br2a
            wf9qFxt4hL5E2eQx7olzTpSLgzA7yUH2wzPD1v8jr+7Kgqa0ZdUv2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T18:59:04Z"
    mac: ENC[AES256_GCM,data:U8Pi4dqVoB74IsUfaZz9dG7L6DBlfwBKAp4FtjdtgzaxpiI/E9KkaofVN8ZV/xOqNSGLUqF7wBgQ2UdryteOSeMxcB9QFk3reysdOHVCmuunLCCSxVIQr3uuv+6GJAzkVL+4IoV/G+L3fZmEdUKll5X46jMJSB3HJn5lTPNAdfA=,iv:InOXOExd+F0xa4HfFUlhfkRHqs8jrEa3OnBRCcz1Lqg=,tag:/v/CsPkbdiNSA8ECqRT94w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
