--- 
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jellyfin
  namespace: media
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteOnce
  mountOptions:
  - nfsvers=4.1
  nfs:
    path: /config/jellyfin
    server: 192.168.0.7

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
