---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  # renovate: datasource=helm depName=cilium repository=https://helm.cilium.io
  version: 1.16.1
  targetNamespace: kube-system
  bootstrap: true
  valuesContent: |-
    autoDirectNodeRoutes: true
    bgpControlPlane:
      enabled: true
    bpf:
      masquerade: false
    cgroup:
      automount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    cluster:
      id: 1
      name: homelab
    cni:
      exclusive: false
      binPath: /var/lib/rancher/k3s/data/current/bin
      confPath: /var/lib/rancher/k3s/agent/etc/cni/net.d
    containerRuntime:
      integration: containerd
      socketPath: /var/run/k3s/containerd/containerd.sock
    # NOTE: devices might need to be set if you have more than one active NIC on your hosts
    # devices: eno+ eth+
    endpointRoutes:
      enabled: true
    hubble:
      enabled: false
    ipam:
      mode: kubernetes
    ipv4NativeRoutingCIDR: "10.69.0.0/16"
    ipv6NativeRoutingCIDR: "fd20:fccd:8001:0::/64"
    ipv6:
      enabled: true
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6444
    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    l2announcements:
      enabled: false # https://github.com/cilium/cilium/issues/28985
    loadBalancer:
      algorithm: maglev
      mode: snat
    localRedirectPolicy: true
    operator:
      replicas: 1
      rollOutPods: true
    rollOutCiliumPods: true
    routingMode: native
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
