apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:dIKAAjb8Mz22rcmaJog0alMnGkcN/3QKIy2e0WnEcQtU7tHibKOZog==,iv:ykiQVdNot2e2sIp67uMBgJeRLefWytYPz1fJwLZh2Zk=,tag:L8V837jAXqCWY5YWG4ibxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdqved3s25mcpgt3r3wgckez60u8jr5aj8espeda88uyh9h3wqpqzj49yr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvL01PdkIyS0RhWVB1OVVh
            cFRwV3NPOE8veG45QU5zWGFoRENXa2d2eXd3ClJNcEdTMU1walhlbVhLaGptMnBm
            VmljZjVaQjBuakx5bVNrdkhyVk1MU1EKLS0tIEZnc3FTem9JM3BNbExSS0FzckRI
            L09FZUJGbFRGTHhhaTZBOEpod0VVbTAKyRrOERYOVv4UH+d7SS0IVlnfJn2v0dCS
            xE+G6uA9OVeKFaMSHy77JW1tC0qCYWE/7A9c9wTZb4riBNq6PEcxvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T19:26:06Z"
    mac: ENC[AES256_GCM,data:UEMOLuRAhuRBvjBmTCDGX/Fkv7/nNsL8ZDkWdqFQlgM4LQ9RIH6hHOyxDodjckjfvpVk+pWfFT9tBYgkD0Unq9m3kNKacqyOlNc1ml7G2CoznthxNep6w2OJLwQ9xL0EY6XxR5sQOQvL1x3Eb+/P1bTC0WbmbUCsfL4IxrDBmrg=,iv:C1v45PfiPHbKk44UrJmtT/9lQGvWHaNARLdA94+nY1Y=,tag:phIg7A8/agf6TXudszIf/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
