apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:FlNCv4pqxRtzWz8WsV9PCyqMJ/bkA2QEsyv1TEFhyS5tvfeubavyBw==,iv:qH/5dPXMFnv18vSRktK4oNu0lMluca9sxZVby+7yO+w=,tag:uBag8Y3zmAKWoS+iRzWpSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdqved3s25mcpgt3r3wgckez60u8jr5aj8espeda88uyh9h3wqpqzj49yr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORlAzOWZyL21tRmxKK0RN
            Mi9uTGdJMnFqaVpFYUZXTGVBeWtGSUNKeDNZCmszc2k0NWhIU1dPTlhKSnVmWVov
            RHlDTzlNRkkxSS9XNURZcE44R0pIVzAKLS0tIGtqVjZoM012Nlc3WitiV2YvSjJW
            Mm82NHFmSmpZY2ZwOS9wK1c3Umx4Z0kK4REzanS0Yzo1vbrBmJ7a5v22xaBCcEHG
            FlTQ+UhbT65Gxwc+qVAvTunZSOI3AVQOANfD9HyLD7yMsjcJwGDRiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-26T12:29:14Z"
    mac: ENC[AES256_GCM,data:Pk4vGHqEG2em5ZWF9/5sToyzesnZSrDAuoTtJvf02x3jikd6e+wB6HiCcTAct7iQXwJRzqwzXdaOr+BaEZ66Rohg2GTd4Kn8WbTQeWqMifrbJr6nPCh4AalMqR4H0v5HokVa5qZy9pxTAkLPZTOYLV+VPeGRX/HkKWnuRjK1I90=,iv:w9GLe92qfPG6f13FURg/1k46e8G70MgfhzTKwGcP5y8=,tag:rmKxTD8O9t/mSORRzUtXfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
