apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:0B1/wFSToX3BisG0YAypF7ghwACVKTMerYAylOOi93VbTBGVO8Gz2w==,iv:qik8WqWVQ2mNKHaFStNzJgtS75sVo1nU2BnFHpBnf7s=,tag:jiBXEdmucAoNEXk9eE3vXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdqved3s25mcpgt3r3wgckez60u8jr5aj8espeda88uyh9h3wqpqzj49yr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVGRWUkxPK0FiYTNzb0Vw
            bEhiaDdab2ZIVnQzUXVlQ0htRFI5ZzRUTTJrCllFemJtb2w3ZUNsVVZVdGRMdWVm
            N0tQcG12Q1VlbTNCRDhIYzhTb2Q0UEUKLS0tIHh5Wm5xTlV1ZmRmOVZCR01aVXh3
            YlFGT3RFaHZldFBKNlR5ZnNuR1dYakEKlZ4ZhbNxsyQ16qhkysx/7Fw3os8bFTAK
            86JzzybiO/4d8ZL7ov4USWx5BvXpMVgqyozn5cx4tSpYMpPGitOfog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T18:09:05Z"
    mac: ENC[AES256_GCM,data:vL15lYh0KQcj3bDBCaLbDgMQfQ8ofkdjexTDI6v3hNNUHcUEnw5D8PWFuPFHRvwD7hdJ5VVh/9NNywrWX9MbUwdjzrzrvg72D+F3bwEHhM3KsnzkKTWdq1+U8jOqs1GtV+f1nc3t7oCc+aZ1tyZRQUf6jOJmtl09S81hZ7JBX+Y=,iv:fQ9JURBHX1Jxr5el9ElSo4hpA+41UNr4XtlzE6V9Vp4=,tag:X+yPHJqH1j5ejTC7vkFZIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
