apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:B5ssqsene1SRErVBOBQUhPa7vcci8ntQRg29CDKajSZc4s3U+aPzBw==,iv:ZJenYTQQqYvyXCEqhNx+W8Zs0Jx5loOK/2BS3iL2xHw=,tag:XH2TtdZE/TYB8PLieynQTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdqved3s25mcpgt3r3wgckez60u8jr5aj8espeda88uyh9h3wqpqzj49yr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbC83VU9VRkNsVzJ6ZE16
            bkdxSjNrcUViRDRoNnJ3MDNlckY0YXhPUWh3CmFSQkRyajFnSzBkOTNwRVJwa0FT
            ZjNHeUtJcHlwTG1MeTd3VUJsV25QVHMKLS0tIEdzZENXcDJxajNKamZ6YWRoZVlB
            NDhWV05obFQ1b3E5SlhabklRdXFBVHMK5Jvg+JnciWulN0WTgG8i79hOMpMeKsRX
            chSjnX1NUBFSSPAPBUMuWDazas+rp/Xw68WmZL8ygfuXkGmqQgD6bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T18:59:04Z"
    mac: ENC[AES256_GCM,data:cHUCU3Ktq3RJjJqMhfGrlSobVPWqG4gLOzE2YpDs8mq16DfnyPt+KM1vEcRRe4spf4zmx847bhHsfL/G4ZHjSGacToRu/GLL6Zj5fCw0arskN+ShcNoe/RwCpxjfJwzqv6VdXIZu9LijwQOu4mdpD3rkMHXw667foeCkwu1+yY0=,iv:77nwebP/4EKhrmV0VBLMVnmAVUkm68v1hh2QsOJqVQE=,tag:8t1t64bv5r0naXTdS3GqbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
