---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      version: v4.8.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system

  maxHistory: 3

  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controller:
      runOnControlPlane: true
    externalSnapshotter:
      enabled: false
    node:
      tolerations: []
