---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-media
provisioner: nfs.csi.k8s.io
parameters:
  server: ${NFS_IP}
  share: /media
reclaimPolicy: Retain
volumeBindingMode: Immediate
# Note: The first two options are strictly for NFSv4.2
mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
