---
connectIPVersion: v4
upstreams:
  groups:
    default:
      - tcp-tls:one.one.one.one
      - tcp-tls:dns.quad9.net
      - https://cloudflare-dns.com/dns-query
      - https://dns.quad9.net/dns-query
  timeout: 2s

bootstrapDns:
  upstream: tcp-tls:one.one.one.one
  ips:
    - 1.1.1.1
    - 1.0.0.1

filtering:
  queryTypes:
    - AAAA
    - HTTPS
# https://github.com/0xERR0R/blocky/issues/1273

blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://adaway.org/hosts.txt
      - https://v.firebog.net/hosts/lists.php?type=nocross
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
      - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
      - https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
      - https://raw.githubusercontent.com/buvis/clusters/main/cluster-home/operations/network/blocky/blacklist.txt
      - https://dbl.oisd.nl/
      - https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/black.list
      - http://sysctl.org/cameleon/hosts
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
      - https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/Blocklist/filter_blocklist1.txt
      - https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/Blocklist/filter_blocklist2.txt
      - https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/Blocklist/filter_blocklist3.txt
      - https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/Blocklist/filter_blocklist4.txt
      - https://raw.githubusercontent.com/kodlz/pihole_easylist/main/adblock_list/adblock.hosts
      - https://raw.githubusercontent.com/herrbischoff/trackers/master/trackers.txt
      - https://raw.githubusercontent.com/herrbischoff/trackers/master/domains.txt
      - https://raw.githubusercontent.com/ftpmorph/ftprivacy/master/blocklists/smartphone-ads-tracking.txt
      - https://codeberg.org/spootle/blocklist/raw/branch/master/blocklist.txt
      - https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/domains.txt
    trackers:
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://v.firebog.net/hosts/Prigent-Ads.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
    noblock: []
  whiteLists:
    ads:
      - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
      - https://raw.githubusercontent.com/larivierec/home-cluster/main/kubernetes/apps/networking/blocky/app/config/whitelist.txt
      - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
      - https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/filter_whitelist.txt
      - https://raw.githubusercontent.com/buvis/clusters/main/cluster-home/operations/network/blocky/whitelist.txt
    trackers:
      - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
      - https://raw.githubusercontent.com/larivierec/home-cluster/main/kubernetes/apps/networking/blocky/app/config/whitelist.txt
    noblock: []
  clientGroupsBlock:
    default:
      - ads
      - trackers

clientLookup:
  upstream: 192.168.0.1
caching:
  prefetching: true
  prefetchExpires: 2h
  minTime: 5m
  cacheTimeNegative: -1m
prometheus:
  enable: true
  path: /metrics
ports:
  dns: 53
  tls: 853
  https: 443
  http: 4000
log:
  level: info
  format: text
