---
apiVersion: v1
kind: Service
metadata:
  name: &app home-assistant
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
      name: https

---
apiVersion: v1
kind: Endpoints
metadata:
  name: home-assistant
  namespace: network
subsets:
- addresses:
  - ip: 192.168.0.2
  ports:
  - port: 443
