---
apiVersion: v1
kind: Service
metadata:
  name: &app home-assistant
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ExternalName

  ports:
    - name: https
      port: 443
  externalName: "ha.local"