---
apiVersion: v1
kind: Service
metadata:
  name: &app home-assistant
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http


