---
apiVersion: v1
kind: Service
metadata:
  name: &app home-assistant
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ExternalName

  ports:
    - name: http
      port: 80
  externalName: "http://192.168.0.2"