apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:PExo+WIY34mIvscpb+h4R1J38cTgQHtu22+DRte7Y8IGEcTNXX4kI4ZCEqpT1MaLOOAl0KuKY12sOisplAJLmC/QDyyUp3SjTU1UX7xSs4VMcIz8gkVQxUtFvVIfvw==,iv:2VDIYiKRaMoHf6Sb1Eech9ejIc6g97cvxNSvK3nNTMw=,tag:nPO8AqxLaJmLiD1G8/ZsuQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:cObt1mnCzY8JxfkMHw==,iv:c+LLrDiFA5YJP+RtwE8NsJTvkCCtRo36XPgOotOfAHg=,tag:uLYQoDduLC536xg39C9ADQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:3317fOLnLapCOkeJ3ISOvkvRAx5m,iv:3HGTqiEaCIyxppsPV5/hfes8jWkmFgzhi4TS/kUX88A=,tag:7WgJG0A8+ruRru2hpWiGSA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:UHQ9aaDJ/t57jpIkrpMiX2uCQVQEgg/1SJNXyH0XgI97CWhW,iv:/lBDOXMixSjrstbzhA+UYzLDt90qAhTcikfpWbRv5Tc=,tag:fnuvUekGvV6U4+og43P76A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdqved3s25mcpgt3r3wgckez60u8jr5aj8espeda88uyh9h3wqpqzj49yr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYjdvRkMycTlJN3dGbG5Y
            aUZsalRSd0x1SFdnRkJrbk1aSitEWHFYVzNVCk0vQW5ILytWeEpWVnlzT2hOcGh3
            T1JLcHNvalhPejdqNmR1SnBDbXFDNGsKLS0tIFlxMjUzaEozZTBpcVNRV2VUbGYw
            WElHUkJ3RFdLOEZydGpZU01XS0NyQzQKun1IoIvaXgv1kRbmGBRAWmVhYWzLndrN
            ltt11TytXFyI1f8aK6WHrAzUCGYfYfW7pp4/dFxnZ12oOvWEyzJqOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T18:59:04Z"
    mac: ENC[AES256_GCM,data:BgLTBpxyRtgIBoctQoQZ4Yvd6wK5eUSBQnfHfcs6VO4AdZoSicPzd3QgFrWn9Zn3eS+tUOta/OYvl6AgA/oCoF8fV6HrdmmG3W32aGwp9ycNlk9d/4gHHC+utOSjQczAq/Tu2F/f5jY3TjDoayhI5+ZxkHX75rEvPcGeUYlE9Tw=,iv:euCp1QKfxF1Hz+gIhORfisyPEREtXVYwljqxRYWge24=,tag:8VA4n0/hpPoc+UDISLB3LA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
