apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:xnTksp7XoJKEcbbzCCFKZQ7f8iDJFStnzsRSTyhmhwE=,iv:HcT5zktXHmSbbxZ8uu0tjRnlsDF+ntRFf3FL673CUu0=,tag:9186F1Akg8Fqx/Pxe0YXkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdqved3s25mcpgt3r3wgckez60u8jr5aj8espeda88uyh9h3wqpqzj49yr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaFZsUkhCMld3YTFxcnhM
            WHNrSTJ2cGV4Y29oMjk2TGg0NnZkRzB1V0c0Ck5abDFPMVZzZnF0cnd5cFg4aW5o
            RVJ2UGxHR3dEQ2Y0UWNpQWpubFZmZGsKLS0tIFFSR25hODdybmU5dnd2azdnUitL
            UVE2TzRUL2x2M3h3bWc4T1ZaeGExWDgKPrIadsVsgIq51ZgiVFDE+PajPXm2Z5wa
            VCk7UVf0WntOne8OqSfCUeeq7ZDJzZymk+lZNJnvgnDFuXZn+S3wMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T18:09:05Z"
    mac: ENC[AES256_GCM,data:fY4aSnoHUmKjD++MvOW4Kj2e6zxsgj2xmhxg7ZrB3hw4hAsZI+DizOYtUIMyf7h2BewSg66RswberSMnXGJw+iwzyHLPUnBJFUf9AeMNLD67K6BvpvZRAPPivBfCYeLtiiAEwLeGB8eWXEZNlDs7fQLpk7F7LgTAesWpQIcaMTg=,iv:ehJBQ955Y19jXQNOfg0fp/Mq6Sx4h9IVwAp8HkUVNZg=,tag:yqe4Lv02SmaugZNw3WA+9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
