apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:bFNiUGbK3Kd9UTTXb/ZvYbmw0pSO2LaCMPHYEsvqmfI=,iv:TAYzsUUCjDcG1iD6/TcYfFKB3SgkKNXZ3mauKIGT0Q8=,tag:a/CjF8ZZ1C0PZVk0FXgIrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdqved3s25mcpgt3r3wgckez60u8jr5aj8espeda88uyh9h3wqpqzj49yr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ2IxdzFXZ3F2S00wRERu
            MzZjdnB2YktvRllCdWJVWHQ2azFYMXBIeVU0CjJPSVVTRVBCZmlGWFhJUWFBM2ZZ
            K2U2R1VES3RrbE5GNG1nMEo4ck5FREUKLS0tIE5GZWhZQWFMcHJ2OHF4WmJpcEZI
            MFBDSEt4eEZ0M1lxeFBTbXh3YlV4SHcKHWD9ibGB9fbBoV7sSR4vAUDCFlTeV/0G
            A4NcedtgHfrpR28R+2E1GZ29X9OhEy904mwzYhHaRrQHb9pflSilHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T19:26:06Z"
    mac: ENC[AES256_GCM,data:fKpzTIBDMUpdiedRn60//lh8/tpuLejnfQGFM02ABbiVihEIFdWsdqKvKMVk6fxe/298kU4F8bYj/iHFSL3jkbrL+AgW6aVCTLTxh/qSyLQj2xc+ZdEg2f9gMID3A9zNAR1Cchh4MNKkUwlqMNsGV8GNT7hgB9eWDIHCOM0oQ14=,iv:y5OEkUa++kJgmiA5gApFqjRh8Iko3e2vCBCU4moz1hM=,tag:HhK1rQRHNMTStqzbJxEBWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
