apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:OVxalD9/NL4gw/jtW0bLegkou+NoHexuRghMGMfC6uzSpVKapXEn2Q==,iv:Ck99C9o6UHmKuvk0KqM5vIIfMqriET2/SHK3rtd/0Ho=,tag:ea6qR7hr7RaZmznqAkWK8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdqved3s25mcpgt3r3wgckez60u8jr5aj8espeda88uyh9h3wqpqzj49yr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNC9rM00xck4zUk5QSG9I
            REFMVHVzZTJyV2pidFp2Vll4Skw4TUtXdWdVCm9oV2Y5T3VodVBDcjQvb2lGTE5V
            R0pNa012MkNlcEdJZlBKbmFJazFOekkKLS0tIEd5SnNhUkFsZnRSZko3Zk9Hak9q
            NGxoVFNkTjNldHBkQTlHc2hVNzlhN0UKc5pMLga+ROJJ0mR2n99PY3IcrH6Emhmh
            wAsIlS6vEz2ZRtZ6vRHEmQB8Rnx6D3YWzdYN7jr1GnBNwKhp4My78g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-26T12:29:14Z"
    mac: ENC[AES256_GCM,data:PbqXB/3+FUPojrYZvck6odvGzzaaMkZraiszZg/kmG9YS4XFL3BYA3nU2BEuQ9/biK9DiMhdqSIHZJVoXKOdGzAX7Pf3HC6tMbHeT4TMGKqMIfzTBiDE0iYdEw7jesCrJBlDu/IsGSJ8m8C+i7yEQ1nuCjHi8dxN7tAzOk2Qu7w=,iv:BnwG0WKURZTt4wziF1T94KdrOC7ycuK1jbg/hrb6U9k=,tag:iQvhLyjsci2CNOYhMRgsdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
