---
apiVersion: v1
kind: Namespace
metadata:
  name: network
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
  annotations:
    lbipam.cilium.io/sharing-cross-namespace: network, flux-system
